#!/usr/bin/env python
#coding=utf-8
from pymouse import PyMouse
from pykeyboard import PyKeyboard

# from sklearn import datasets
# iris = datasets.load_iris()
# print iris.data
m = PyMouse()
k = PyKeyboard()
x_dim, y_dim = m.screen_size()
print x_dim,y_dim
m.click(x_dim/2, y_dim/2, 1)
k.tap_key('3')